{% set name = "skyfield-data" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98f63b44a433d455857fc05fc71fe54c03fd4799dc8516cc2b0d509bea67263b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - skyfield_data

about:
  home: https://github.com/brunobord/skyfield-data
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Data files for Skyfield

extra:
  recipe-maintainers:
    - Matt-BF
